#pragma once

#define FEATURE_WIFI 1
#define FEATURE_TIME 1
#define FEATURE_MQTT 1
#define FEATURE_HA 1
#define FEATURE_IO 1
#define FEATURE_POOL_DEVICE 1
#define FEATURE_POOL_LOGIC 1
#define FEATURE_HMI 1
#define FEATURE_SUPERVISOR_HMI 0
#define FEATURE_WEB 1
#define FEATURE_FW_UPDATE 1
#define FEATURE_I2C_CFG_SERVER 0
#define FEATURE_I2C_CFG_CLIENT 0
#define FEATURE_WIFI_PROVISIONING 1
